/* Реестр инструментов ForgeKit: категории, инструменты, поиск */

import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import type { LucideIcon } from "lucide-react";
import {
  ArrowDownAZ,
  Binary,
  Braces,
  CalendarClock,
  CalendarDays,
  CaseSensitive,
  ClipboardList,
  Cpu,
  Crop,
  EyeOff,
  FileCog,
  FileOutput,
  FileSearch,
  FileStack,
  FileText,
  Files,
  Fingerprint,
  FolderTree,
  GitCompare,
  Globe,
  Globe2,
  Hash,
  Image,
  ImageDown,
  ImagePlus,
  Info,
  KeyRound,
  KeySquare,
  Languages,
  LayoutDashboard,
  Link,
  Lock,
  Minimize2,
  MonitorCog,
  Network,
  PenLine,
  PieChart,
  Pilcrow,
  Pipette,
  Puzzle,
  QrCode,
  Regex,
  Scale,
  Scissors,
  ScrollText,
  Settings,
  ShieldCheck,
  Sigma,
  Split,
  TextSelect,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

export interface ToolDef {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  keywords: string[];
  category: string;
  categoryName: string;
  component: LazyExoticComponent<ComponentType>;
}

export interface CategoryDef {
  id: string;
  name: string;
  icon: LucideIcon;
  toolIds: string[];
}

const lazyTool = (id: string) => lazy(() => import(`../tools/${id}.tsx`).then((m) => ({ default: m.default })));

export const TOOLS: ToolDef[] = [
  /* --- Dashboard / Буфер --- */
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Обзор и быстрые действия",
    icon: LayoutDashboard,
    keywords: ["главная", "старт", "обзор", "dashboard", "home"],
    category: "dashboard",
    categoryName: "Dashboard",
    component: lazyTool("Dashboard"),
  },
  {
    id: "clipboard",
    name: "Clipboard History",
    description: "История буфера обмена с поиском, закреплением и избранным",
    icon: ClipboardList,
    keywords: ["буфер", "обмена", "история", "копирование", "clipboard", "copy", "paste"],
    category: "clipboard",
    categoryName: "Clipboard History",
    component: lazyTool("ClipboardHistory"),
  },

  /* --- Файлы --- */
  {
    id: "duplicate-finder",
    name: "Поиск дубликатов",
    description: "Находит повторяющиеся файлы по хэшу содержимого",
    icon: FileSearch,
    keywords: ["дубликаты", "файлы", "поиск", "хэш", "duplicate"],
    category: "files",
    categoryName: "Файлы",
    component: lazyTool("DuplicateFinder"),
  },
  {
    id: "bulk-rename",
    name: "Массовое переименование",
    description: "Переименовывает сразу все файлы в папке по шаблону",
    icon: PenLine,
    keywords: ["переименование", "rename", "шаблон", "папка", "batch"],
    category: "files",
    categoryName: "Файлы",
    component: lazyTool("BulkRename"),
  },
  {
    id: "file-organizer",
    name: "Организация файлов",
    description: "Раскладывает файлы по папкам по типу или расширению",
    icon: FolderTree,
    keywords: ["организация", "папки", "сортировка", "organize", "move"],
    category: "files",
    categoryName: "Файлы",
    component: lazyTool("FileOrganizer"),
  },
  {
    id: "file-size-analyzer",
    name: "Анализ размера файлов",
    description: "Показывает, какие файлы и папки занимают больше всего места",
    icon: PieChart,
    keywords: ["размер", "анализ", "место", "диск", "size", "storage"],
    category: "files",
    categoryName: "Файлы",
    component: lazyTool("FileSizeAnalyzer"),
  },

  /* --- Разработка --- */
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Форматирование и валидация JSON-данных",
    icon: Braces,
    keywords: ["json", "форматирование", "валидация", "pretty"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("JSONFormatter"),
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Сравнение двух JSON или текстовых версий",
    icon: GitCompare,
    keywords: ["json", "diff", "сравнение", "различия"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("JSONDiff"),
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Проверка регулярных выражений в реальном времени",
    icon: Regex,
    keywords: ["regex", "регулярные", "выражения", "тест"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("RegexTester"),
  },
  {
    id: "hash-generator",
    name: "Генератор хэшей",
    description: "MD5, SHA-1, SHA-256, SHA-512 для любой строки",
    icon: Fingerprint,
    keywords: ["хэш", "md5", "sha", "хеширование", "hash"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("HashGenerator"),
  },
  {
    id: "uuid",
    name: "UUID Generator",
    description: "Генерация UUID v4 и v7",
    icon: Hash,
    keywords: ["uuid", "guid", "идентификатор", "генератор"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("UUIDGenerator"),
  },
  {
    id: "base64",
    name: "Base64 Encoder",
    description: "Кодирование и декодирование Base64",
    icon: Binary,
    keywords: ["base64", "кодирование", "декодирование", "encode"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("Base64Encoder"),
  },
  {
    id: "url-codec",
    name: "URL Codec",
    description: "Кодирование и декодирование URL-строк",
    icon: Link,
    keywords: ["url", "кодирование", "uri", "percent", "encode"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("URLCodec"),
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Расшифровка заголовка и payload JWT-токена",
    icon: KeyRound,
    keywords: ["jwt", "token", "токен", "декодирование", "payload"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("JWTDecoder"),
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Редактор Markdown с предпросмотром",
    icon: ScrollText,
    keywords: ["markdown", "md", "превью", "предпросмотр", "разметка"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("MarkdownPreview"),
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Разбор cron-выражений и ближайшие запуски",
    icon: CalendarClock,
    keywords: ["cron", "расписание", "парсер", "задачи", "schedule"],
    category: "developer",
    categoryName: "Разработка",
    component: lazyTool("CronParser"),
  },

  /* --- Система --- */
  {
    id: "system-info",
    name: "Сведения о системе",
    description: "ОС, процессор, память, диски и время работы",
    icon: MonitorCog,
    keywords: ["система", "информация", "oc", "процессор", "память", "system"],
    category: "system",
    categoryName: "Система",
    component: lazyTool("SystemInfo"),
  },
  {
    id: "process-viewer",
    name: "Процессы",
    description: "Список запущенных процессов и их использование памяти",
    icon: Cpu,
    keywords: ["процессы", "pid", "память", "task", "process"],
    category: "system",
    categoryName: "Система",
    component: lazyTool("ProcessViewer"),
  },
  {
    id: "unit-converter",
    name: "Конвертер единиц",
    description: "Длина, вес, данные, скорость, температура, площадь",
    icon: Scale,
    keywords: ["конвертер", "единицы", "длина", "вес", "температура"],
    category: "system",
    categoryName: "Система",
    component: lazyTool("UnitConverter"),
  },
  {
    id: "date-time-converter",
    name: "Конвертер дат",
    description: "Unix-время, ISO 8601, локальные форматы дат",
    icon: CalendarDays,
    keywords: ["дата", "время", "unix", "timestamp", "iso"],
    category: "system",
    categoryName: "Система",
    component: lazyTool("DateTimeConverter"),
  },

  /* --- Сеть --- */
  {
    id: "ping",
    name: "Ping",
    description: "Проверка доступности хоста и задержки",
    icon: Wifi,
    keywords: ["ping", "доступность", "задержка", "хост", "сеть"],
    category: "network",
    categoryName: "Сеть",
    component: lazyTool("Ping"),
  },
  {
    id: "port-scanner",
    name: "Сканер портов",
    description: "Проверка открытых портов на хосте",
    icon: Network,
    keywords: ["порты", "сканер", "port", "scan", "tcp"],
    category: "network",
    categoryName: "Сеть",
    component: lazyTool("PortScanner"),
  },
  {
    id: "ip-lookup",
    name: "Мой IP",
    description: "Определение публичного IP-адреса",
    icon: Globe,
    keywords: ["ip", "адрес", "публичный", "внешний", "lookup"],
    category: "network",
    categoryName: "Сеть",
    component: lazyTool("IPLookup"),
  },
  {
    id: "http-status",
    name: "HTTP Status Codes",
    description: "Справочник кодов ответов HTTP",
    icon: Globe2,
    keywords: ["http", "коды", "статус", "404", "200", "ошибки"],
    category: "network",
    categoryName: "Сеть",
    component: lazyTool("HTTPStatus"),
  },
  {
    id: "whois",
    name: "WHOIS",
    description: "Информация о домене: владелец, даты, серверы",
    icon: FileSearch,
    keywords: ["whois", "домен", "регистрация", "владелец"],
    category: "network",
    categoryName: "Сеть",
    component: lazyTool("Whois"),
  },

  /* --- Безопасность --- */
  {
    id: "password-generator",
    name: "Генератор паролей",
    description: "Надёжные пароли с настраиваемым набором символов",
    icon: KeySquare,
    keywords: ["пароль", "генератор", "password", "сложный"],
    category: "security",
    categoryName: "Безопасность",
    component: lazyTool("PasswordGenerator"),
  },
  {
    id: "password-strength",
    name: "Проверка пароля",
    description: "Оценка надёжности пароля по набору критериев",
    icon: ShieldCheck,
    keywords: ["пароль", "надёжность", "сила", "strength", "проверка"],
    category: "security",
    categoryName: "Безопасность",
    component: lazyTool("PasswordStrength"),
  },
  {
    id: "aes-encrypt",
    name: "AES Шифрование",
    description: "AES-256-GCM шифрование и расшифровка текста",
    icon: Lock,
    keywords: ["aes", "шифрование", "encrypt", "ключ", "gcm"],
    category: "security",
    categoryName: "Безопасность",
    component: lazyTool("AESEncrypt"),
  },
  {
    id: "text-obfuscator",
    name: "Маскировка текста",
    description: "Преобразование текста в набор цифр и символов",
    icon: EyeOff,
    keywords: ["маскировка", "обфускация", "текст", "скрыть", "obfuscate"],
    category: "security",
    categoryName: "Безопасность",
    component: lazyTool("TextObfuscator"),
  },

  /* --- Графика --- */
  {
    id: "color-picker",
    name: "Палитра цветов",
    description: "Конвертация HEX, RGB, HSL и CMYK",
    icon: Pipette,
    keywords: ["цвет", "hex", "rgb", "hsl", "cmyk", "палитра"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("ColorPicker"),
  },
  {
    id: "image-converter",
    name: "Конвертер изображений",
    description: "PNG, JPEG, WebP, GIF, BMP, TIFF — любой формат в любой",
    icon: ImageDown,
    keywords: ["изображение", "конвертация", "png", "jpeg", "webp"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("ImageConverter"),
  },
  {
    id: "image-compressor",
    name: "Сжатие изображений",
    description: "Уменьшение размера JPG, PNG и WebP с выбором качества",
    icon: Minimize2,
    keywords: ["сжатие", "компрессия", "размер", "качество", "jpeg"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("ImageCompressor"),
  },
  {
    id: "image-resizer",
    name: "Изменение размера",
    description: "Масштабирование изображений под нужные размеры",
    icon: Crop,
    keywords: ["размер", "масштаб", "resize", "пиксели", "изображение"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("ImageResizer"),
  },
  {
    id: "qr-generator",
    name: "QR-коды",
    description: "Генерация QR-кода из текста или ссылки",
    icon: QrCode,
    keywords: ["qr", "код", "генератор", "ссылка", "barcode"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("QRGenerator"),
  },
  {
    id: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Минификация SVG-разметки: убирает пробелы и комментарии",
    icon: Zap,
    keywords: ["svg", "оптимизация", "минификация", "разметка"],
    category: "graphics",
    categoryName: "Графика",
    component: lazyTool("SVGOptimizer"),
  },

  /* --- Текст --- */
  {
    id: "case-converter",
    name: "Конвертер регистра",
    description: "UPPER, lower, Title Case, camelCase, snake_case и другие",
    icon: CaseSensitive,
    keywords: ["регистр", "case", "uppercase", "lowercase", "camel"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("CaseConverter"),
  },
  {
    id: "text-counter",
    name: "Счётчик текста",
    description: "Символы, слова, строки, предложения и другая статистика",
    icon: Sigma,
    keywords: ["счётчик", "символы", "слова", "статистика", "counter"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("TextCounter"),
  },
  {
    id: "text-diff",
    name: "Сравнение текстов",
    description: "Построчное сравнение двух версий текста",
    icon: Split,
    keywords: ["сравнение", "diff", "различия", "текст", "версии"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("TextDiff"),
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Генератор текста-заглушки для вёрстки",
    icon: TextSelect,
    keywords: ["lorem", "ipsum", "заглушка", "текст", "генератор"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("LoremIpsum"),
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Транслитерация и создание URL-slug из названий",
    icon: Pilcrow,
    keywords: ["slug", "транслитерация", "url", "название", "ссылка"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("SlugGenerator"),
  },
  {
    id: "alphabetizer",
    name: "Сортировка строк",
    description: "Алфавитная сортировка, по длине, удаление дубликатов",
    icon: ArrowDownAZ,
    keywords: ["сортировка", "алфавит", "строки", "алфавитизация", "sort"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("Alphabetizer"),
  },
  {
    id: "unicode-info",
    name: "Unicode Info",
    description: "Коды символов: Unicode, эскейпы, десятичные значения",
    icon: Languages,
    keywords: ["unicode", "символы", "коды", "escaped", "codepoint"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("UnicodeInfo"),
  },
  {
    id: "regex-replace",
    name: "Regex Replace",
    description: "Поиск и замена текста по регулярному выражению",
    icon: Wrench,
    keywords: ["regex", "замена", "поиск", "регулярные", "replace"],
    category: "text",
    categoryName: "Текст",
    component: lazyTool("RegexReplace"),
  },

  /* --- PDF --- */
  {
    id: "pdf-merge",
    name: "Объединение PDF",
    description: "Склейка нескольких PDF-файлов в один документ",
    icon: FileStack,
    keywords: ["pdf", "объединение", "merge", "склейка", "страницы"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("PDFMerge"),
  },
  {
    id: "pdf-split",
    name: "Разделение PDF",
    description: "Разрезка PDF на части по диапазонам страниц",
    icon: Scissors,
    keywords: ["pdf", "разделение", "split", "диапазон", "страницы"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("PDFSplit"),
  },
  {
    id: "pdf-info",
    name: "Информация о PDF",
    description: "Страницы, версия, метаданные документа",
    icon: FileText,
    keywords: ["pdf", "информация", "метаданные", "страницы", "info"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("PDFInfo"),
  },
  {
    id: "image-to-pdf",
    name: "Изображение в PDF",
    description: "Сборка изображений в один PDF-документ",
    icon: ImagePlus,
    keywords: ["pdf", "изображение", "конвертация", "картинки", "image"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("ImageToPDF"),
  },
  {
    id: "pdf-to-images",
    name: "PDF в изображения",
    description: "Рендер каждой страницы PDF в PNG (требуется poppler)",
    icon: FileOutput,
    keywords: ["pdf", "изображения", "png", "рендер", "страницы"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("PDFToImages"),
  },
  {
    id: "pdf-compress",
    name: "Оптимизация PDF",
    description: "Уменьшение размера PDF за счёт удаления лишних объектов",
    icon: FileCog,
    keywords: ["pdf", "сжатие", "оптимизация", "размер", "compress"],
    category: "documents",
    categoryName: "PDF",
    component: lazyTool("PDFCompress"),
  },

  /* --- Системные страницы --- */
  {
    id: "plugins",
    name: "Плагины",
    description: "Модули расширения ForgeKit",
    icon: Puzzle,
    keywords: ["плагины", "модули", "расширения", "plugins"],
    category: "settings",
    categoryName: "Настройки",
    component: lazyTool("Plugins"),
  },
  {
    id: "settings",
    name: "Настройки",
    description: "Параметры приложения",
    icon: Settings,
    keywords: ["настройки", "параметры", "settings", "конфигурация"],
    category: "settings",
    categoryName: "Настройки",
    component: lazyTool("Settings"),
  },
  {
    id: "about",
    name: "О приложении",
    description: "Версия и информация о ForgeKit",
    icon: Info,
    keywords: ["о приложении", "версия", "about", "информация"],
    category: "settings",
    categoryName: "Настройки",
    component: lazyTool("About"),
  },
];

const TOOL_MAP = new Map(TOOLS.map((t) => [t.id, t]));

export function getTool(id: string): ToolDef {
  return TOOL_MAP.get(id) ?? TOOLS[0];
}

export const CATEGORIES: CategoryDef[] = [
  { id: "dashboard", name: "Dashboard", icon: LayoutDashboard, toolIds: ["dashboard"] },
  { id: "clipboard", name: "Clipboard History", icon: ClipboardList, toolIds: ["clipboard"] },
  { id: "files", name: "Файлы", icon: Files, toolIds: ["duplicate-finder", "bulk-rename", "file-organizer", "file-size-analyzer"] },
  { id: "developer", name: "Разработка", icon: Braces, toolIds: ["json-formatter", "json-diff", "regex-tester", "hash-generator", "uuid", "base64", "url-codec", "jwt-decoder", "markdown-preview", "cron-parser"] },
  { id: "system", name: "Система", icon: Cpu, toolIds: ["system-info", "process-viewer", "unit-converter", "date-time-converter"] },
  { id: "network", name: "Сеть", icon: Wifi, toolIds: ["ping", "port-scanner", "ip-lookup", "http-status", "whois"] },
  { id: "security", name: "Безопасность", icon: ShieldCheck, toolIds: ["password-generator", "password-strength", "aes-encrypt", "text-obfuscator"] },
  { id: "graphics", name: "Графика", icon: Image, toolIds: ["color-picker", "image-converter", "image-compressor", "image-resizer", "qr-generator", "svg-optimizer"] },
  { id: "text", name: "Текст", icon: TextSelect, toolIds: ["case-converter", "text-counter", "text-diff", "lorem-ipsum", "slug-generator", "alphabetizer", "unicode-info", "regex-replace"] },
  { id: "documents", name: "PDF", icon: FileStack, toolIds: ["pdf-merge", "pdf-split", "pdf-info", "image-to-pdf", "pdf-to-images", "pdf-compress"] },
  { id: "plugins", name: "Плагины", icon: Puzzle, toolIds: ["plugins"] },
  { id: "settings", name: "Настройки", icon: Settings, toolIds: ["settings", "about"] },
];

const CATEGORY_MAP = new Map(CATEGORIES.map((c) => [c.id, c]));

export function getCategory(id: string): CategoryDef | undefined {
  return CATEGORY_MAP.get(id);
}

export const FEATURED_TOOLS: string[] = [
  "clipboard",
  "json-formatter",
  "image-converter",
  "password-generator",
  "pdf-merge",
  "hash-generator",
];
